=== billpwchan/SCADA-nsl/softs/SCADAsoft/5.3.1/dat/dtd/dbkclass.dtd
<!-- DtdVersion='2.3' -->
<!ELEMENT Class (ClassDescription|AttributeDescription*)>
<!ATTLIST Class
	name CDATA #REQUIRED
	numInstances CDATA #REQUIRED
	numAttributes CDATA #REQUIRED
	period_ST CDATA #REQUIRED
	numPeriod_ST CDATA #REQUIRED
	period_MT CDATA #REQUIRED
	numPeriod_MT CDATA #REQUIRED
	capacity CDATA #IMPLIED
>
<!ELEMENT ClassDescription (AttributeDescription*)>
<!ELEMENT AttributeDescription ((Scalar, ScalarDefaultValue?) | (Vector, VectorDefaultValue?) | (StructVector, StructVectorDefaultValue?))>
<!ATTLIST AttributeDescription
	name CDATA #REQUIRED
	attrType (STATIC | VOLATILE | HISTORIC_ST | HISTORIC_MT | HISTORIC_CHB) #REQUIRED
	replicated (0 | 1) #REQUIRED
>
<!ELEMENT Scalar EMPTY>
<!ATTLIST Scalar
	size CDATA #REQUIRED
	valueType (BOOLEAN | INT8 | UINT8 | INT16 | UINT16 | INT32 | UINT32 | INT64 | UINT64 | FLOAT | DOUBLE | COMPLEX | CHARN | REFERENCE | DATE | SHORTDATE | BITFIELD) #REQUIRED
>
<!ELEMENT ScalarDefaultValue EMPTY>
<!ATTLIST ScalarDefaultValue
	defaultValue CDATA #REQUIRED
>
<!ELEMENT Vector (Scalar)>
<!ATTLIST Vector
	numElements CDATA #REQUIRED
>
<!ELEMENT VectorDefaultValue (ScalarDefaultValue+)>
<!ATTLIST VectorDefaultValue
	numElements CDATA #REQUIRED
>
<!ELEMENT StructVector (StructFieldDescription+)>
<!ATTLIST StructVector
	numElementsList CDATA #REQUIRED
	numElementsStruct CDATA #REQUIRED
>
<!ELEMENT StructFieldDescription (Scalar)>
<!ATTLIST StructFieldDescription
	name CDATA #REQUIRED
>
<!ELEMENT StructVectorDefaultValue (StructFieldDefaultValue+)>
<!ATTLIST StructVectorDefaultValue
	numElementsList CDATA #REQUIRED
>
<!ELEMENT StructFieldDefaultValue (ScalarDefaultValue+)>

=== billpwchan/SCADA-nsl/scspaths/OCCENV/Database/xml/aio_type.xml
<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE Class SYSTEM "dtd/dbkclass.dtd">
<Class name="aio_type" numAttributes="39" numInstances="0" numPeriod_MT="0" numPeriod_ST="0" period_MT="0" period_ST="0">
<AttributeDescription attrType="STATIC" name="initCondTable" replicated="0">
<StructVector numElementsList="8" numElementsStruct="2">
<StructFieldDescription name="condInfo">
<Scalar size="31" valueType="CHARN"/>
</StructFieldDescription>
<StructFieldDescription name="condVal">
<Scalar size="1" valueType="BOOLEAN"/>
</StructFieldDescription>
</StructVector>
<StructVectorDefaultValue numElementsList="8">
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue="false"/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue="false"/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue="false"/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue="false"/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue="false"/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue="false"/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue="false"/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue="false"/>
</StructFieldDefaultValue>
</StructVectorDefaultValue>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="retCondTable" replicated="0">
<StructVector numElementsList="8" numElementsStruct="2">
<StructFieldDescription name="condInfo">
<Scalar size="31" valueType="CHARN"/>
</StructFieldDescription>
<StructFieldDescription name="condVal">
<Scalar size="1" valueType="BOOLEAN"/>
</StructFieldDescription>
</StructVector>
<StructVectorDefaultValue numElementsList="8">
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue="false"/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue="false"/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue="false"/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue="false"/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue="false"/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue="false"/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue="false"/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue="false"/>
</StructFieldDefaultValue>
</StructVectorDefaultValue>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="UNIVNAME" replicated="0">
<Scalar size="65" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="class_id" replicated="0">
<Scalar size="21" valueType="CHARN"/>
<ScalarDefaultValue defaultValue="108"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="computedMessage" replicated="0">
<Scalar size="257" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="execStatus" replicated="0">
<Scalar size="4" valueType="INT32"/>
<ScalarDefaultValue defaultValue="0"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="hmiOrder" replicated="0">
<Scalar size="4" valueType="INT32"/>
<ScalarDefaultValue defaultValue="0"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="initCond1" replicated="0">
<Scalar size="1" valueType="BOOLEAN"/>
<ScalarDefaultValue defaultValue="1"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="initCond2" replicated="0">
<Scalar size="1" valueType="BOOLEAN"/>
<ScalarDefaultValue defaultValue="1"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="initCond3" replicated="0">
<Scalar size="1" valueType="BOOLEAN"/>
<ScalarDefaultValue defaultValue="1"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="initCond4" replicated="0">
<Scalar size="1" valueType="BOOLEAN"/>
<ScalarDefaultValue defaultValue="1"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="initCond5" replicated="0">
<Scalar size="1" valueType="BOOLEAN"/>
<ScalarDefaultValue defaultValue="1"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="initCond6" replicated="0">
<Scalar size="1" valueType="BOOLEAN"/>
<ScalarDefaultValue defaultValue="1"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="initCond7" replicated="0">
<Scalar size="1" valueType="BOOLEAN"/>
<ScalarDefaultValue defaultValue="1"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="initCond8" replicated="0">
<Scalar size="1" valueType="BOOLEAN"/>
<ScalarDefaultValue defaultValue="1"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="initCondGL" replicated="0">
<Scalar size="1" valueType="BOOLEAN"/>
<ScalarDefaultValue defaultValue="false"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="initCondTO" replicated="0">
<Scalar size="4" valueType="INT32"/>
<ScalarDefaultValue defaultValue="0"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="label" replicated="0">
<Scalar size="65" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="nom_instance" replicated="0">
<Scalar size="51" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="opDate" replicated="0">
<Scalar size="8" valueType="DATE"/>
<ScalarDefaultValue defaultValue="01/01/2000 00:00:00.000"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="opSource" replicated="0">
<Scalar size="9" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="previousStatus" replicated="0">
<Scalar size="4" valueType="INT32"/>
<ScalarDefaultValue defaultValue="0"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="previousValue" replicated="0">
<Scalar size="4" valueType="FLOAT"/>
<ScalarDefaultValue defaultValue="0.0"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="returnCond1" replicated="0">
<Scalar size="1" valueType="BOOLEAN"/>
<ScalarDefaultValue defaultValue="1"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="returnCond2" replicated="0">
<Scalar size="1" valueType="BOOLEAN"/>
<ScalarDefaultValue defaultValue="1"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="returnCond3" replicated="0">
<Scalar size="1" valueType="BOOLEAN"/>
<ScalarDefaultValue defaultValue="1"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="returnCond4" replicated="0">
<Scalar size="1" valueType="BOOLEAN"/>
<ScalarDefaultValue defaultValue="1"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="returnCond5" replicated="0">
<Scalar size="1" valueType="BOOLEAN"/>
<ScalarDefaultValue defaultValue="1"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="returnCond6" replicated="0">
<Scalar size="1" valueType="BOOLEAN"/>
<ScalarDefaultValue defaultValue="1"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="returnCond7" replicated="0">
<Scalar size="1" valueType="BOOLEAN"/>
<ScalarDefaultValue defaultValue="1"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="returnCond8" replicated="0">
<Scalar size="1" valueType="BOOLEAN"/>
<ScalarDefaultValue defaultValue="1"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="returnCondGL" replicated="0">
<Scalar size="1" valueType="BOOLEAN"/>
<ScalarDefaultValue defaultValue="false"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="returnCondTO" replicated="0">
<Scalar size="4" valueType="INT32"/>
<ScalarDefaultValue defaultValue="0"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="source" replicated="0">
<Scalar size="9" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="status" replicated="0">
<Scalar size="4" valueType="INT32"/>
<ScalarDefaultValue defaultValue="1"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="unit" replicated="0">
<Scalar size="21" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="value" replicated="0">
<Scalar size="4" valueType="FLOAT"/>
<ScalarDefaultValue defaultValue="0.0"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="valueLimits" replicated="0">
<Vector numElements="2">
<Scalar size="4" valueType="FLOAT"/>
</Vector>
<VectorDefaultValue>
<ScalarDefaultValue defaultValue="0.0"/>
<ScalarDefaultValue defaultValue="0.0"/>
</VectorDefaultValue>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="veCoord" replicated="0">
<Scalar size="81" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
</Class>

=== billpwchan/SCADA-nsl/scspaths/OCCENV/Database/xml/sac_type.xml
<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE Class SYSTEM "dtd/dbkclass.dtd">
<Class name="sac_type" numAttributes="9" numInstances="524" numPeriod_MT="0" numPeriod_ST="0" period_MT="0" period_ST="0">
<AttributeDescription attrType="STATIC" name="veTable" replicated="0">
<StructVector numElementsList="4" numElementsStruct="6">
<StructFieldDescription name="date">
<Scalar size="8" valueType="DATE"/>
</StructFieldDescription>
<StructFieldDescription name="status">
<Scalar size="4" valueType="INT32"/>
</StructFieldDescription>
<StructFieldDescription name="value1">
<Scalar size="256" valueType="BITFIELD"/>
</StructFieldDescription>
<StructFieldDescription name="value2">
<Scalar size="256" valueType="BITFIELD"/>
</StructFieldDescription>
<StructFieldDescription name="vename">
<Scalar size="49" valueType="CHARN"/>
</StructFieldDescription>
<StructFieldDescription name="vepole">
<Scalar size="31" valueType="CHARN"/>
</StructFieldDescription>
</StructVector>
<StructVectorDefaultValue numElementsList="4">
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue="01/01/2000 00:00:00.000"/>
<ScalarDefaultValue defaultValue="0"/>
<ScalarDefaultValue defaultValue="0"/>
<ScalarDefaultValue defaultValue="0"/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue="01/01/2000 00:00:00.000"/>
<ScalarDefaultValue defaultValue="0"/>
<ScalarDefaultValue defaultValue="0"/>
<ScalarDefaultValue defaultValue="0"/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue="01/01/2000 00:00:00.000"/>
<ScalarDefaultValue defaultValue="0"/>
<ScalarDefaultValue defaultValue="0"/>
<ScalarDefaultValue defaultValue="0"/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue="01/01/2000 00:00:00.000"/>
<ScalarDefaultValue defaultValue="0"/>
<ScalarDefaultValue defaultValue="0"/>
<ScalarDefaultValue defaultValue="0"/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
</StructVectorDefaultValue>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="UNIVNAME" replicated="0">
<Scalar size="65" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="acqDate" replicated="0">
<Scalar size="8" valueType="DATE"/>
<ScalarDefaultValue defaultValue="01/01/2000 00:00:00.000"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="acqStatus" replicated="0">
<Scalar size="4" valueType="INT32"/>
<ScalarDefaultValue defaultValue="0"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="acqValue" replicated="0">
<Vector numElements="2">
<Scalar size="256" valueType="BITFIELD"/>
</Vector>
<VectorDefaultValue>
<ScalarDefaultValue defaultValue="0"/>
<ScalarDefaultValue defaultValue="0"/>
</VectorDefaultValue>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="class_id" replicated="0">
<Scalar size="4" valueType="INT32"/>
<ScalarDefaultValue defaultValue="207"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="equipmentDate" replicated="0">
<Scalar size="8" valueType="DATE"/>
<ScalarDefaultValue defaultValue="01/01/2000 00:00:00.000"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="nom_instance" replicated="0">
<Scalar size="51" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="period" replicated="0">
<Scalar size="4" valueType="INT32"/>
<ScalarDefaultValue defaultValue="0"/>
</AttributeDescription>
</Class>

=== billpwchan/SCADA-nsl/scspaths/OCCENV/Database/xml/ufe_date.xml
<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE Class SYSTEM "dtd/dbkclass.dtd">
<Class name="ufe_date" numAttributes="5" numInstances="24" numPeriod_MT="" numPeriod_ST="" period_MT="" period_ST="">
<AttributeDescription attrType="STATIC" name="UNIVNAME" replicated="0">
<Scalar size="65" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="label" replicated="0">
<Scalar size="65" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="nom_instance" replicated="0">
<Scalar size="51" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="value" replicated="0">
<Scalar size="8" valueType="DATE"/>
<ScalarDefaultValue defaultValue="01/01/2000 00:00:00.000"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="computedValue" replicated="0">
<Scalar size="8" valueType="DATE"/>
<ScalarDefaultValue defaultValue="01/01/2000 00:00:00.000"/>
</AttributeDescription>
</Class>

=== billpwchan/SCADA-nsl/scspaths/OCCENV/Database/xml/ScadaSoft.xml
<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE Class SYSTEM "dtd/dbkclass.dtd">
<Class name="ScadaSoft" numAttributes="5" numInstances="1" numPeriod_MT="0" numPeriod_ST="0" period_MT="0" period_ST="0">
<AttributeDescription attrType="STATIC" name="UNIVNAME" replicated="0">
<Scalar size="65" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="dbvDate" replicated="0">
<Scalar size="8" valueType="DATE"/>
<ScalarDefaultValue defaultValue="01/01/2000 00:00:00.000"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="dbvName" replicated="0">
<Scalar size="65" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="dpcTrigger" replicated="0">
<Scalar size="4" valueType="INT32"/>
<ScalarDefaultValue defaultValue="0"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="nom_instance" replicated="0">
<Scalar size="51" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
</Class>

=== billpwchan/SCADA-nsl/scspaths/OCCENV/Database/xml.bak/LstTag14.xml
<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE Class SYSTEM "dtd/dbkclass.dtd">
<Class name="LstTag14" numAttributes="4" numInstances="0" numPeriod_MT="" numPeriod_ST="" period_MT="" period_ST="">
<AttributeDescription attrType="STATIC" name="UNIVNAME" replicated="0">
<Scalar size="65" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="nom_instance" replicated="0">
<Scalar size="51" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="parentID" replicated="0">
<Scalar size="65" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="type" replicated="0">
<Scalar size="65" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
</Class>

=== billpwchan/SCADA-nsl/scspaths/OCCENV/Database/xml.bak/clScsAlarm.xml
<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE Class SYSTEM "dtd/dbkclass.dtd">
<Class name="clScsAlarm" numAttributes="4" numInstances="1" numPeriod_MT="0" numPeriod_ST="0" period_MT="0" period_ST="0">
<AttributeDescription attrType="STATIC" name="format" replicated="0">
<StructVector numElementsList="50" numElementsStruct="3">
<StructFieldDescription name="dataDisplay">
<Scalar size="257" valueType="CHARN"/>
</StructFieldDescription>
<StructFieldDescription name="dataDispo">
<Scalar size="257" valueType="CHARN"/>
</StructFieldDescription>
<StructFieldDescription name="dataType">
<Scalar size="257" valueType="CHARN"/>
</StructFieldDescription>
</StructVector>
<StructVectorDefaultValue numElementsList="50">
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
<StructFieldDefaultValue>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
<ScalarDefaultValue defaultValue=""/>
</StructFieldDefaultValue>
</StructVectorDefaultValue>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="UNIVNAME" replicated="0">
<Scalar size="65" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="nom_instance" replicated="0">
<Scalar size="51" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="resetSynthesis" replicated="0">
<Scalar size="4" valueType="INT32"/>
<ScalarDefaultValue defaultValue="0"/>
</AttributeDescription>
</Class>

=== billpwchan/SCADA-nsl/scspaths/OCCENV/Database/xml/cmb_type.xml
<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE Class SYSTEM "dtd/dbkclass.dtd">
<Class name="cmb_type" numAttributes="5" numInstances="0" numPeriod_MT="" numPeriod_ST="" period_MT="" period_ST="">
<AttributeDescription attrType="STATIC" name="UNIVNAME" replicated="0">
<Scalar size="65" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="nom_instance" replicated="0">
<Scalar size="51" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="Trigger1" replicated="0">
<Scalar size="4" valueType="INT32"/>
<ScalarDefaultValue defaultValue="0"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="Trigger2" replicated="0">
<Scalar size="4" valueType="INT32"/>
<ScalarDefaultValue defaultValue="0"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="combinedStatus" replicated="0">
<Scalar size="4" valueType="INT32"/>
<ScalarDefaultValue defaultValue="0"/>
</AttributeDescription>
</Class>
