=== billpwchan/SCADA-nsl/softs/SCADAsoft/5.3.1/dat/dtd/dbkclass.dtd
<!-- DtdVersion='2.3' -->
<!ELEMENT Class (ClassDescription|AttributeDescription*)>
<!ATTLIST Class
	name CDATA #REQUIRED
	numInstances CDATA #REQUIRED
	numAttributes CDATA #REQUIRED
	period_ST CDATA #REQUIRED
	numPeriod_ST CDATA #REQUIRED
	period_MT CDATA #REQUIRED
	numPeriod_MT CDATA #REQUIRED
	capacity CDATA #IMPLIED
>
<!ELEMENT ClassDescription (AttributeDescription*)>
<!ELEMENT AttributeDescription ((Scalar, ScalarDefaultValue?) | (Vector, VectorDefaultValue?) | (StructVector, StructVectorDefaultValue?))>
<!ATTLIST AttributeDescription
	name CDATA #REQUIRED
	attrType (STATIC | VOLATILE | HISTORIC_ST | HISTORIC_MT | HISTORIC_CHB) #REQUIRED
	replicated (0 | 1) #REQUIRED
>
<!ELEMENT Scalar EMPTY>
<!ATTLIST Scalar
	size CDATA #REQUIRED
	valueType (BOOLEAN | INT8 | UINT8 | INT16 | UINT16 | INT32 | UINT32 | INT64 | UINT64 | FLOAT | DOUBLE | COMPLEX | CHARN | REFERENCE | DATE | SHORTDATE | BITFIELD) #REQUIRED
>
<!ELEMENT ScalarDefaultValue EMPTY>
<!ATTLIST ScalarDefaultValue
	defaultValue CDATA #REQUIRED
>
<!ELEMENT Vector (Scalar)>
<!ATTLIST Vector
	numElements CDATA #REQUIRED
>
<!ELEMENT VectorDefaultValue (ScalarDefaultValue+)>
<!ATTLIST VectorDefaultValue
	numElements CDATA #REQUIRED
>
<!ELEMENT StructVector (StructFieldDescription+)>
<!ATTLIST StructVector
	numElementsList CDATA #REQUIRED
	numElementsStruct CDATA #REQUIRED
>
<!ELEMENT StructFieldDescription (Scalar)>
<!ATTLIST StructFieldDescription
	name CDATA #REQUIRED
>
<!ELEMENT StructVectorDefaultValue (StructFieldDefaultValue+)>
<!ATTLIST StructVectorDefaultValue
	numElementsList CDATA #REQUIRED
>
<!ELEMENT StructFieldDefaultValue (ScalarDefaultValue+)>

=== billpwchan/SCADA-nsl/scspaths/OCCENV/Database/xml/basicNode.xml
<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE Class SYSTEM "dtd/dbkclass.dtd">
<Class name="basicNode" numAttributes="9" numInstances="66" numPeriod_MT="" numPeriod_ST="" period_MT="" period_ST="">
<AttributeDescription attrType="STATIC" name="UNIVNAME" replicated="0">
<Scalar size="65" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="alarmSynthesis" replicated="0">
<Vector numElements="4">
<Scalar size="4" valueType="INT32"/>
</Vector>
<VectorDefaultValue>
<ScalarDefaultValue defaultValue="0"/>
<ScalarDefaultValue defaultValue="0"/>
<ScalarDefaultValue defaultValue="0"/>
<ScalarDefaultValue defaultValue="0"/>
</VectorDefaultValue>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="functionalCat" replicated="0">
<Scalar size="4" valueType="INT32"/>
<ScalarDefaultValue defaultValue="0"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="geographicalCat" replicated="0">
<Scalar size="4" valueType="INT32"/>
<ScalarDefaultValue defaultValue="0"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="label" replicated="0">
<Scalar size="65" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="name" replicated="0">
<Scalar size="65" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="nom_instance" replicated="0">
<Scalar size="51" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="prevAlarmSynthesis" replicated="0">
<Vector numElements="4">
<Scalar size="4" valueType="INT32"/>
</Vector>
<VectorDefaultValue>
<ScalarDefaultValue defaultValue="0"/>
<ScalarDefaultValue defaultValue="0"/>
<ScalarDefaultValue defaultValue="0"/>
<ScalarDefaultValue defaultValue="0"/>
</VectorDefaultValue>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="type" replicated="0">
<Scalar size="21" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
</Class>

=== billpwchan/SCADA-nsl/scspaths/OCCENV/Database/xml/ModeGroup.xml
<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE Class SYSTEM "dtd/dbkclass.dtd">
<Class name="ModeGroup" numAttributes="7" numInstances="0" numPeriod_MT="" numPeriod_ST="" period_MT="" period_ST="">
<AttributeDescription attrType="STATIC" name="UNIVNAME" replicated="0">
<Scalar size="65" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="computedDate" replicated="0">
<Scalar size="8" valueType="DATE"/>
<ScalarDefaultValue defaultValue="01/01/2000 00:00:00.000"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="computedStatus" replicated="0">
<Scalar size="4" valueType="INT32"/>
<ScalarDefaultValue defaultValue="0"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="computedValue" replicated="0">
<Scalar size="4" valueType="INT32"/>
<ScalarDefaultValue defaultValue="0"/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="label" replicated="0">
<Scalar size="129" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="nom_instance" replicated="0">
<Scalar size="51" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
<AttributeDescription attrType="STATIC" name="type" replicated="0">
<Scalar size="33" valueType="CHARN"/>
<ScalarDefaultValue defaultValue=""/>
</AttributeDescription>
</Class>
